services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: live-message
    volumes:
      - /data/databases/falbue/test/postgres:/var/lib/postgres
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - db-net

networks:
  db-net:
